# generated by generate.rb
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main cursor)
typeset -gA ZSH_HIGHLIGHT_STYLES

# Main highlighter styling: https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md
#
## Comments
ZSH_HIGHLIGHT_STYLES[comment]='fg=#{{colors.comment}}'
## Functions/methods
ZSH_HIGHLIGHT_STYLES[alias]='fg=#{{colors.green}}'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=#{{colors.green}}'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=#{{colors.green}}'
ZSH_HIGHLIGHT_STYLES[function]='fg=#{{colors.green}}'
ZSH_HIGHLIGHT_STYLES[command]='fg=#{{colors.green}}'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#{{colors.green}},italic'
ZSH_HIGHLIGHT_STYLES[autodirectory]='fg=#{{colors.white}},italic'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#{{colors.white}}'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#{{colors.white}}'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#{{colors.purple}}'
## Built ins
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#{{colors.green}}'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#{{colors.green}}'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=#{{colors.green}}'
## Punctuation
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#{{colors.error}}'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg=#{{colors.text}}'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-unquoted]='fg=#{{colors.text}}'
ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]='fg=#{{colors.text}}'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]='fg=#{{colors.error}}'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=#{{colors.error}}'
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#{{colors.error}}'
## Strings
ZSH_HIGHLIGHT_STYLES[command-substitution-quoted]='fg=#{{colors.yellow}}'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-quoted]='fg=#{{colors.yellow}}'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#{{colors.yellow}}'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#{{colors.red}}'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#{{colors.yellow}}'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#{{colors.red}}'
ZSH_HIGHLIGHT_STYLES[rc-quote]='fg=#{{colors.yellow}}'
## Variables
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#{{colors.text}}'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#{{colors.red}}'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#{{colors.text}}'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#{{colors.text}}'
ZSH_HIGHLIGHT_STYLES[named-fd]='fg=#{{colors.text}}'
ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=#{{colors.text}}'
## No category relevant in spec
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#{{colors.red}}'
ZSH_HIGHLIGHT_STYLES[path]='fg=#{{colors.accent}},underline'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=#{{colors.grey_dim}},underline'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=#{{colors.text}},underline'
ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]='fg=#{{colors.grey_dim}},underline'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#{{colors.text}}'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=#{{colors.purple}}'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-unclosed]='fg=#{{colors.red}}'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#{{colors.text}}'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=#{{colors.text}}'
ZSH_HIGHLIGHT_STYLES[default]='fg=#{{colors.text}}'
ZSH_HIGHLIGHT_STYLES[cursor]='fg=#{{colors.text}}'
