-- generated by generate.rb

local M = {}

M.colors = {
  fg         = "#{{colors.fg}}",
  bg         = "#{{colors.bg}}",
  bg_dim     = "#{{colors.bg_dim}}",
  bg_bright  = "#{{colors.bg_bright}}",
  black      = "#{{colors.black}}",
  white      = "#{{colors.white}}",
  grey       = "#{{colors.grey}}",
  red        = "#{{colors.red}}",
  orange     = "#{{colors.orange}}",
  yellow     = "#{{colors.yellow}}",
  green      = "#{{colors.green}}",
  cyan       = "#{{colors.cyan}}",
  blue       = "#{{colors.blue}}",
  purple     = "#{{colors.purple}}",
  pink       = "#{{colors.pink}}",
  bright_white  = "#{{colors.bright_white}}",
  bright_red    = "#{{colors.bright_red}}",
  bright_orange = "#{{colors.bright_orange}}",
  bright_yellow = "#{{colors.bright_yellow}}",
  bright_green  = "#{{colors.bright_green}}",
  bright_cyan   = "#{{colors.bright_cyan}}",
  bright_blue   = "#{{colors.bright_blue}}",
  bright_purple = "#{{colors.bright_purple}}",
  primary = "#{{colors.primary}}",
  path    = "#{{colors.path}}",
  accent  = "#{{colors.accent}}",
  grey_dim = "#{{colors.grey_dim}}",
  error   = "#{{colors.error}}",
  comment = "#{{colors.comment}}"
}

M.wezterm = "{{wezterm.theme}}"
M.nvim    = "{{nvim.theme}}"
M.lualine = "{{nvim.lualine}}"
M.vivid   = "{{vivid.theme}}"

return M
