# generated by generate.rb
export VIVID_THEME="{{vivid.theme}}"
export BAT_THEME="{{bat.theme}}"

# LESS_TERMCAP for search highlighting in pagers
export LESS_TERMCAP_so=$'{{less.search_bg}}{{less.search_fg}}'
export LESS_TERMCAP_se=$'\e[0m'
