"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[ui]
diff-editor = ["nvim", "--cmd", "let g:_no_session = 1", "-c", "DiffEditor $left $right $output"]
diff-instructions = false
# default-command = ["log", "-r", "local_stack"]
# merge-editor = ["nvim", "-c", "DiffviewOpen"]

[revset-aliases]
"recent" = "ancestors(@, 20)"
"stack" = "immutable_heads()..@"
"local_stack" = "ancestors(@, 8) | (ancestors(@, 8):: & ~immutable())"

[colors]
"diff added" = {fg = "bright green", bold = true}
"diff modified" = {fg = "bright cyan"}
"diff renamed" = {fg = "bright yellow", bold = true}

[templates]
draft_commit_description = "builtin_draft_commit_description_with_diff"

[aliases]
logs = ["log", "-r", "stack"]

[snapshot]
max-new-gile-size = "3MiB"
