"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[ui]
default-command = "status"

[revset-aliases]
"recent" = "ancestors(@, 20)"
"stack" = "immutable_heads()..@"

[aliases]
logs = ["log", "-r", "stack"]
