-- generated by generate.rb

local M = {}

M.colors = {
  fg         = "#DCD7BA",
  bg         = "#1F1F28",
  bg_dim     = "#2A2A37",
  bg_bright  = "#363646",
  black      = "#16161D",
  white      = "#C8C093",
  grey       = "#727169",
  red        = "#C34043",
  orange     = "#ffa066",
  yellow     = "#C0A36E",
  green      = "#76946A",
  cyan       = "#6a9589",
  blue       = "#7E9CD8",
  purple     = "#957FB8",
  pink       = "#D27E99",
  bright_white  = "#DCD7BA",
  bright_red    = "#E82424",
  bright_orange = "#ff5d62",
  bright_yellow = "#e6c384",
  bright_green  = "#98bb6c",
  bright_cyan   = "#7aa89f",
  bright_blue   = "#7fb4ca",
  bright_purple = "#938aa9",
  primary = "#7E9CD8",
  path    = "#D27E99",
  accent  = "#957FB8",
  grey_dim = "#54546D",
  error   = "#E82424",
  comment = "#727169"
}

M.wezterm = "Kanagawa (Gogh)"
M.nvim    = "kanagawa-wave"
M.lualine = "kanagawa"
M.vivid   = "tokyonight-storm"

return M
