# Generated ZSH Syntax Highlighting Theme
#
# This file is auto-generated by theme/generate-omp-theme.rb
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main cursor)
typeset -gA ZSH_HIGHLIGHT_STYLES

# Main highlighter styling: https://github.com/zsh-users/zsh-syntax-highlighting/blob/master/docs/highlighters/main.md
#
## General
### Diffs
### Markup
## Classes
## Comments
ZSH_HIGHLIGHT_STYLES[comment]='fg=#727169'
## Constants
## Entitites
## Functions/methods
ZSH_HIGHLIGHT_STYLES[alias]='fg=#76946A'
ZSH_HIGHLIGHT_STYLES[suffix-alias]='fg=#76946A'
ZSH_HIGHLIGHT_STYLES[global-alias]='fg=#76946A'
ZSH_HIGHLIGHT_STYLES[function]='fg=#76946A'
ZSH_HIGHLIGHT_STYLES[command]='fg=#76946A'
ZSH_HIGHLIGHT_STYLES[precommand]='fg=#76946A,italic'
ZSH_HIGHLIGHT_STYLES[autodirectory]='fg=#C8C093,italic'
ZSH_HIGHLIGHT_STYLES[single-hyphen-option]='fg=#C8C093'
ZSH_HIGHLIGHT_STYLES[double-hyphen-option]='fg=#C8C093'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument]='fg=#957FB8'
## Keywords
## Built ins
ZSH_HIGHLIGHT_STYLES[builtin]='fg=#76946A'
ZSH_HIGHLIGHT_STYLES[reserved-word]='fg=#76946A'
ZSH_HIGHLIGHT_STYLES[hashed-command]='fg=#76946A'
## Punctuation
ZSH_HIGHLIGHT_STYLES[commandseparator]='fg=#E82424'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter]='fg=#DCD7BA'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-unquoted]='fg=#DCD7BA'
ZSH_HIGHLIGHT_STYLES[process-substitution-delimiter]='fg=#DCD7BA'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-delimiter]='fg=#E82424'
ZSH_HIGHLIGHT_STYLES[back-double-quoted-argument]='fg=#E82424'
ZSH_HIGHLIGHT_STYLES[back-dollar-quoted-argument]='fg=#E82424'
## Serializable / Configuration Languages
## Storage
## Strings
ZSH_HIGHLIGHT_STYLES[command-substitution-quoted]='fg=#C0A36E'
ZSH_HIGHLIGHT_STYLES[command-substitution-delimiter-quoted]='fg=#C0A36E'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=#C0A36E'
ZSH_HIGHLIGHT_STYLES[single-quoted-argument-unclosed]='fg=#C34043'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=#C0A36E'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument-unclosed]='fg=#C34043'
ZSH_HIGHLIGHT_STYLES[rc-quote]='fg=#C0A36E'
## Variables
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument]='fg=#DCD7BA'
ZSH_HIGHLIGHT_STYLES[dollar-quoted-argument-unclosed]='fg=#C34043'
ZSH_HIGHLIGHT_STYLES[dollar-double-quoted-argument]='fg=#DCD7BA'
ZSH_HIGHLIGHT_STYLES[assign]='fg=#DCD7BA'
ZSH_HIGHLIGHT_STYLES[named-fd]='fg=#DCD7BA'
ZSH_HIGHLIGHT_STYLES[numeric-fd]='fg=#DCD7BA'
## No category relevant in spec
ZSH_HIGHLIGHT_STYLES[unknown-token]='fg=#C34043'
ZSH_HIGHLIGHT_STYLES[path]='fg=#957FB8,underline'
ZSH_HIGHLIGHT_STYLES[path_pathseparator]='fg=#D27E99,underline'
ZSH_HIGHLIGHT_STYLES[path_prefix]='fg=#DCD7BA,underline'
ZSH_HIGHLIGHT_STYLES[path_prefix_pathseparator]='fg=#DCD7BA,underline'
ZSH_HIGHLIGHT_STYLES[globbing]='fg=#DCD7BA'
ZSH_HIGHLIGHT_STYLES[history-expansion]='fg=#957FB8'
#ZSH_HIGHLIGHT_STYLES[command-substitution]='fg=?'
#ZSH_HIGHLIGHT_STYLES[command-substitution-unquoted]='fg=?'
#ZSH_HIGHLIGHT_STYLES[process-substitution]='fg=?'
#ZSH_HIGHLIGHT_STYLES[arithmetic-expansion]='fg=?'
ZSH_HIGHLIGHT_STYLES[back-quoted-argument-unclosed]='fg=#C34043'
ZSH_HIGHLIGHT_STYLES[redirection]='fg=#DCD7BA'
ZSH_HIGHLIGHT_STYLES[arg0]='fg=#DCD7BA'
ZSH_HIGHLIGHT_STYLES[default]='fg=#DCD7BA'
ZSH_HIGHLIGHT_STYLES[cursor]='fg=#DCD7BA'
