# generated by ai
# Powerlevel10k prompt — replicates the previous oh-my-posh kanagawa look.
# Rendered from template/zsh/p10k.zsh (kanagawa-wave palette). If you switch
# themes with generate.py this file is regenerated; the source of truth is the
# template. Two-line, plain (no backgrounds) prompt:
#   line 1:  os_icon  user@host   path   [jj | git]   time
#   line 2:  (exit-code-on-error)  prompt-char

'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  local primary='#7E9CD8'
  local path_c='#D27E99'
  local accent='#957FB8'
  local muted='#54546D'
  local error='#E82424'

  # ------------------------------------------------------------------ layout
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon context dir jj vcs time
    newline status prompt_char
  )
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()

  # plain style: no backgrounds, no powerline separators, single-space joins
  typeset -g POWERLEVEL9K_BACKGROUND=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_MIDDLE_WHITESPACE=' '
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=
  typeset -g POWERLEVEL9K_VISUAL_IDENTIFIER_EXPANSION=

  # blank line before each prompt (mirrors the old precmd newline hook)
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=

  # --------------------------------------------------------------- os_icon
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=$primary
  typeset -g POWERLEVEL9K_OS_ICON_CONTENT_EXPANSION=$'\uf179'  # nf-fa-apple

  # --------------------------------------------------------------- context
  typeset -g POWERLEVEL9K_ALWAYS_SHOW_CONTEXT=true
  typeset -g POWERLEVEL9K_ALWAYS_SHOW_USER=true
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=$primary
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=$primary
  typeset -g POWERLEVEL9K_CONTEXT_SUDO_FOREGROUND=$primary
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_SUDO_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_REMOTE_TEMPLATE='(ssh) %n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_REMOTE_SUDO_TEMPLATE='(ssh) %n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_VISUAL_IDENTIFIER_EXPANSION=

  # --------------------------------------------------------------- dir
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=$path_c
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=0
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=
  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=false
  typeset -g POWERLEVEL9K_DIR_VISUAL_IDENTIFIER_EXPANSION=''

  # --------------------------------------------------------------- vcs (git)
  # uses the gitstatus daemon: no per-prompt git fork.
  typeset -g POWERLEVEL9K_VCS_BACKENDS=(git)
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON=$'\U000F062C '
  typeset -g POWERLEVEL9K_VCS_VISUAL_IDENTIFIER_EXPANSION=
  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=$accent
  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=$accent
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=$accent
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_FOREGROUND=$accent
  typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=$muted
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
  typeset -g POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN=''

  # --------------------------------------------------------------- time
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=$muted
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%l:%M %p}'
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false
  typeset -g POWERLEVEL9K_TIME_VISUAL_IDENTIFIER_EXPANSION='󱑍'

  # --------------------------------------------------------------- status (exit code)
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_ERROR=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=$error
  typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION=
  typeset -g POWERLEVEL9K_STATUS_ERROR_CONTENT_EXPANSION='(${P9K_CONTENT})'
  typeset -g POWERLEVEL9K_STATUS_VERBOSE=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
  typeset -g POWERLEVEL9K_STATUS_HIDE_SIGNAME=true
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE=false
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true

  # --------------------------------------------------------------- prompt char
  typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=$accent
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=$accent
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_{VIINS,VICMD,VIVIS,VIOWR}_CONTENT_EXPANSION='󰧂'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_{LEFT,RIGHT}_WHITESPACE=

  # --------------------------------------------------------------- jj (custom)
  typeset -g POWERLEVEL9K_JJ_FOREGROUND=$accent
  typeset -g POWERLEVEL9K_JJ_VISUAL_IDENTIFIER_EXPANSION='󰁥'

  function prompt_jj() {
    [[ -n $_p9k_jj_root ]] || return
    local info
    info=$(command jj log --no-graph --ignore-working-copy --color never -r @ \
      -T 'separate(" ", bookmarks, change_id.shortest(8), if(empty, "", "±"))' 2>/dev/null) || return
    [[ -n $info ]] || return
    # color and icon come from POWERLEVEL9K_JJ_{FOREGROUND,VISUAL_IDENTIFIER_EXPANSION}
    p10k segment -t "${info//\%/%%}"
  }
  function instant_prompt_jj() { prompt_jj }

  # per-prompt: detect jj repo root (cheap, no fork) and toggle git suppression
  typeset -g _p9k_jj_root=
  _p9k_jj_detect() {
    _p9k_jj_root=
    local d=$PWD
    while [[ -n $d ]]; do
      if [[ -d $d/.jj ]]; then _p9k_jj_root=$d; break; fi
      d=${d%/*}
    done
    if [[ -n $_p9k_jj_root ]]; then
      typeset -g POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN='*'
    else
      typeset -g POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN=''
    fi
  }
  autoload -Uz add-zsh-hook
  add-zsh-hook precmd _p9k_jj_detect
  # the detection must run BEFORE p10k builds the prompt (_p9k_precmd), so the
  # git-suppression pattern and jj info are fresh for the current prompt.
  precmd_functions=(${precmd_functions:#_p9k_jj_detect})
  local -a _p9k_pf=() _f
  for _f in $precmd_functions; do
    [[ $_f == _p9k_precmd ]] && _p9k_pf+=_p9k_jj_detect
    _p9k_pf+=$_f
  done
  precmd_functions=($_p9k_pf)

  # ------------------------------------------------------------------ misc
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=verbose
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  (( ! $+functions[p10k] )) || p10k reload
}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
