-- dims the bg of non-current windows by defining NormalNC
-- generated by ai
-- note: NormalNC applies to all non-current windows, not just normal buftypes
local util = require("util")

util.on_colorscheme(function()
  vim.fn.writefile({ "debug" }, "/tmp/dim", "a")
  local normal = vim.api.nvim_get_hl(0, { name = "Normal" })
  if normal.bg then
    vim.api.nvim_set_hl(0, "NormalNC", {
      fg = normal.fg,
      bg = util.blend(normal.bg, 0, 0.3),
    })
  end
end)
