-- generated by ai
-- per-window history of visited files; navigate with <M-o>/<M-i>

-- keyed by winid: { files = {bufnr, ...}, idx = N }
local win_history = {}
local navigating = false

local function is_real_buf(bufnr)
  return vim.api.nvim_buf_is_valid(bufnr)
    and vim.bo[bufnr].buftype == ""
    and vim.api.nvim_buf_get_name(bufnr) ~= ""
end

local function get_hist(winid)
  if not win_history[winid] then
    win_history[winid] = { files = {}, idx = 0 }
  end
  return win_history[winid]
end

local function record(bufnr)
  if navigating then return end
  if not is_real_buf(bufnr) then return end
  local winid = vim.api.nvim_get_current_win()
  local hist = get_hist(winid)
  -- ignore if same as current entry
  if hist.idx > 0 and hist.files[hist.idx] == bufnr then return end
  -- truncate forward history on new navigation
  for i = hist.idx + 1, #hist.files do
    hist.files[i] = nil
  end
  table.insert(hist.files, bufnr)
  hist.idx = #hist.files
end

local function go(delta)
  local winid = vim.api.nvim_get_current_win()
  local hist = win_history[winid]
  if not hist then return end
  local target = hist.idx + delta
  while target >= 1 and target <= #hist.files do
    local bufnr = hist.files[target]
    if vim.api.nvim_buf_is_valid(bufnr) then
      navigating = true
      hist.idx = target
      pcall(vim.api.nvim_win_set_buf, winid, bufnr)
      navigating = false
      return
    end
    -- skip over deleted buffers
    target = target + delta
  end
end

vim.api.nvim_create_autocmd("BufEnter", {
  callback = function(args) record(args.buf) end,
})

vim.api.nvim_create_autocmd("WinClosed", {
  callback = function(args) win_history[tonumber(args.match)] = nil end,
})

local function show()
  local winid = vim.api.nvim_get_current_win()
  local hist = win_history[winid]
  if not hist or #hist.files == 0 then
    print("No file history")
    return
  end
  local lines = { " count  file" }
  for i, bufnr in ipairs(hist.files) do
    local name = vim.api.nvim_buf_is_valid(bufnr)
        and vim.fn.fnamemodify(vim.api.nvim_buf_get_name(bufnr), ":~")
      or "[deleted]"
    local rel = i - hist.idx
    local marker = i == hist.idx and ">" or " "
    table.insert(lines, string.format("%s %5d  %s", marker, rel, name))
  end
  print(table.concat(lines, "\n"))
end

vim.keymap.set("n", "<M-o>", function() go(-1) end, { desc = "File history: backward" })
vim.keymap.set("n", "<M-i>", function() go(1) end, { desc = "File history: forward" })
vim.api.nvim_create_user_command("FileJumps", show, { desc = "Show per-window file history" })
vim.api.nvim_create_user_command("ClearFileJumps", function()
  local winid = vim.api.nvim_get_current_win()
  win_history[winid] = nil
end, { desc = "Clear per-window file history" })
