-- generated by ai
local util = require("util")

---@return integer? start_row 0-indexed
---@return integer? start_col 0-indexed
---@return integer? end_row 0-indexed
---@return integer? end_col 0-indexed inclusive
local function find_sql_statement_range()
  local node = vim.treesitter.get_node()
  if not node then
    return
  end

  local parser = vim.treesitter.get_parser(0)
  if not parser then
    return
  end
  local root = parser:parse()[1]:root()

  -- do nothing if on root node (toplevel semicolon or whitespace)
  if node == root then
    return
  end

  -- walk up to direct child of root
  local cur = node
  while cur:parent() and cur:parent() ~= root do
    cur = cur:parent()
  end
  if cur == root then
    return
  end

  -- index all root-level children for boundary scanning
  local children = {}
  for child in root:iter_children() do
    table.insert(children, child)
  end

  local cur_idx
  for i, child in ipairs(children) do
    if child == cur then
      cur_idx = i
      break
    end
  end
  if not cur_idx then
    return
  end

  local function is_semicolon(idx)
    local c = children[idx]
    return c and not c:named() and vim.treesitter.get_node_text(c, 0) == ";"
  end

  -- scan back to find start of logical statement (right after previous ";")
  local start_idx = cur_idx
  while start_idx > 1 and not is_semicolon(start_idx - 1) do
    start_idx = start_idx - 1
  end
  -- skip any leading unnamed nodes (e.g. whitespace after ";")
  while start_idx <= #children and not children[start_idx]:named() do
    start_idx = start_idx + 1
  end
  if start_idx > #children then
    return
  end

  -- scan forward counting ";" to find the end of the Nth statement (for count support)
  local end_idx = cur_idx
  local semi_count = 0
  while end_idx <= #children do
    if is_semicolon(end_idx) then
      semi_count = semi_count + 1
      if semi_count >= vim.v.count1 then
        break
      end
    end
    end_idx = end_idx + 1
  end
  end_idx = math.min(end_idx, #children)

  -- if no ";" found (unterminated last statement), trim trailing unnamed nodes
  if not is_semicolon(end_idx) then
    while end_idx > start_idx and not children[end_idx]:named() do
      end_idx = end_idx - 1
    end
  end

  local start_row, start_col = children[start_idx]:range()
  local _, _, er, ec = children[end_idx]:range()

  -- treesitter end is exclusive; ec==0 means the node ends at the start of the next line
  local end_row, end_col
  if ec == 0 then
    local line = vim.api.nvim_buf_get_lines(0, er - 1, er, true)[1] or ""
    end_row, end_col = er - 1, math.max(0, #line - 1)
  else
    end_row, end_col = er, ec - 1
  end

  return start_row, start_col, end_row, end_col
end

-- visually select the statement under the cursor
local function select_sql_statement()
  local start_row, start_col, end_row, end_col = find_sql_statement_range()
  if not start_row then
    return
  end
  vim.api.nvim_win_set_cursor(0, { start_row + 1, start_col })
  vim.cmd("normal! v")
  vim.api.nvim_win_set_cursor(0, { end_row + 1, end_col })
end

-- exit any open pager (q) and clear partial input (ctrl-u) before sending
---@param text string
local function psql_send(text)
  util.kitty_send("PSQL", "q\x15" .. text)
end

-- send the statement under the cursor to kitty psql
local function send_statement_to_psql()
  local start_row, start_col, end_row, end_col = find_sql_statement_range()
  if not start_row then
    return
  end
  local lines = vim.api.nvim_buf_get_text(0, start_row, start_col, end_row, end_col + 1, {})
  psql_send(table.concat(lines, "\n"))
end

-- send the current visual selection to kitty psql
local function send_visual_to_psql()
  local region = vim.fn.getregion(vim.fn.getpos("'<"), vim.fn.getpos("'>"), { type = vim.fn.visualmode() })
  psql_send(table.concat(region, "\n"))
end

vim.api.nvim_create_autocmd("FileType", {
  pattern = { "sql", "plsql", "mysql" },
  callback = function()
    vim.keymap.set("n", "<leader>vs", select_sql_statement, { buffer = true, desc = "select sql statement" })
    vim.keymap.set("n", "<d-cr>", send_statement_to_psql, { buffer = true, desc = "send sql statement to psql" })
    vim.keymap.set("x", "<d-cr>", send_visual_to_psql, { buffer = true, desc = "send selection to psql" })
  end,
})
