-- generated by ai
local scratch_dir = vim.fn.expand("~/.local/state/nvim/scratch")

-- encode cwd as a flat filename; escape existing ! first, then replace /
local function scratch_path()
  local cwd = vim.fn.getcwd()
  local encoded = cwd:gsub("!", "!!"):gsub("/", "!")
  return scratch_dir .. "/" .. encoded .. ".md"
end

local scratch_buf = nil

local function save_scratch()
  if scratch_buf and vim.api.nvim_buf_is_valid(scratch_buf) and vim.bo[scratch_buf].modified then
    vim.api.nvim_buf_call(scratch_buf, function()
      vim.cmd("silent! write")
    end)
  end
end

local function open_scratch()
  vim.fn.mkdir(scratch_dir, "p")

  if scratch_buf and vim.api.nvim_buf_is_valid(scratch_buf) then
    local wins = vim.fn.win_findbuf(scratch_buf)
    if #wins > 0 then
      vim.api.nvim_set_current_win(wins[1])
    else
      vim.api.nvim_set_current_buf(scratch_buf)
    end
    return
  end

  vim.cmd("edit " .. vim.fn.fnameescape(scratch_path()))
  scratch_buf = vim.api.nvim_get_current_buf()

  vim.api.nvim_create_autocmd("BufHidden", {
    buffer = scratch_buf,
    callback = save_scratch,
  })
end

-- FocusLost: save while scratch is visible but vim loses focus
-- VimLeavePre: save when scratch is the last buffer (BufHidden won't fire)
vim.api.nvim_create_autocmd({ "FocusLost", "VimLeavePre" }, {
  callback = save_scratch,
})

vim.api.nvim_create_user_command("Scratch", open_scratch, {})
