vim.pack.add({ 'https://github.com/gbprod/substitute.nvim' })
require('substitute').setup()
vim.keymap.set("n", "<d-s>", require("substitute").operator, { desc = "Substitute" })
vim.keymap.set("n", "<d-S>", require("substitute").line, { desc = "Substitute line" })
vim.keymap.set("n", "S", require("substitute").eol, { desc = "Substitute eol" })
vim.keymap.set("x", "s", require("substitute").visual, { desc = "Substitute" })
