-- generated by ai
-- set @# (alternate file) to sveltekit companion so <C-^> toggles between them

local companions = {
  ["+page.svelte"]      = "+layout.svelte",
  ["+layout.svelte"]    = "+page.svelte",
  ["+page.server.ts"]   = "+page.svelte",
  ["+page.ts"]          = "+page.svelte",
  ["+layout.server.ts"] = "+layout.svelte",
  ["+layout.ts"]        = "+layout.svelte",
}

vim.api.nvim_create_autocmd("BufEnter", {
  pattern = vim.tbl_keys(companions),
  callback = function()
    local current = vim.fn.expand("%:t")
    local dir = vim.fn.expand("%:h")
    local target = companions[current]
    if not target then return end
    local path = dir .. "/" .. target
    if vim.fn.filereadable(path) == 1 then
      vim.fn.setreg("#", vim.fn.bufadd(path))
    end
  end,
})
