-- generated by ai
return {
  "milanglacier/yarepl.nvim",
  config = function()
    local yarepl = require("yarepl")

    yarepl.setup({
      -- open REPL in a horizontal split at the bottom (like toggleterm)
      wincmd = "belowright 15 split",
      metas = {
        aichat = false,
        radian = false,
        ipython = false,
        python = false,
        R = false,
        bash = false,
        psql = {
          -- use $DATABASE_URL if set, otherwise prompt
          cmd = function()
            local default = os.getenv("DATABASE_URL") or ""
            local url = vim.fn.input("PostgreSQL URL: ", default)
            local test = url == "" and { "psql", "--command", "\\q" } or { "psql", url, "--command", "\\q" }
            local result = vim.fn.system(test)
            if vim.v.shell_error ~= 0 then
              vim.schedule(function()
                vim.notify("psql: " .. vim.trim(result), vim.log.levels.ERROR)
              end)
              return { "sh", "-c", "exit 0" }
            end
            return url == "" and { "psql" } or { "psql", url }
          end,
          formatter = "bracketed_pasting",
        },
        sqlite = {
          cmd = function()
            local default = os.getenv("DATABASE_URL") or ""
            local db = vim.fn.input("SQLite file: ", default, "file")
            local rlwrap = { "rlwrap", "--always-readline", "--no-children" }
            if db == "" then
              return vim.list_extend(rlwrap, { "sqlite3" })
            end
            return vim.list_extend(rlwrap, { "sqlite3", db })
          end,
          formatter = "trim_empty_lines",
        },
      },
    })

    vim.api.nvim_create_user_command("PG", "REPLStart psql", {})
    vim.api.nvim_create_user_command("SQLITE", "REPLStart sqlite", {})

    -- use <leader>x group (already registered as "Execute" in which-key)
    local map = function(mode, lhs, rhs, desc)
      vim.keymap.set(mode, lhs, rhs, { desc = desc })
    end
    map("n", "<leader>xp", "<cmd>REPLStart psql<cr>", "Start psql REPL")
    map("n", "<leader>xP", "<cmd>REPLStart sqlite<cr>", "Start sqlite REPL")
    map("n", "<leader>xf", "<cmd>REPLFocus psql<cr>", "Focus psql REPL")
    map("n", "<leader>xh", "<cmd>REPLHide psql<cr>", "Hide psql REPL")
    map("n", "<leader>xl", "<cmd>REPLSendLine<cr>", "Send line to REPL")
    map("n", "<leader>xm", "<cmd>REPLSendOperator<cr>", "Send motion to REPL")
    map("v", "<leader>xv", ":<c-u>REPLSendVisual<cr>", "Send selection to REPL")
  end,
}
