-- generated by ai
local helpers = require("config.lualine.helpers")

local M = {}

local jj_head = ""
local jj_repo_status = { added = 0, modified = 0, removed = 0, conflicts = 0 }
local jj_head_job = nil
local jj_status_job = nil

local function update_jj_status()
  if not helpers.is_jj_repo() then
    jj_head = ""
    jj_repo_status = { added = 0, modified = 0, removed = 0, conflicts = 0 }
    return
  end

  if jj_head_job then
    vim.fn.jobstop(jj_head_job)
  end
  if jj_status_job then
    vim.fn.jobstop(jj_status_job)
  end

  -- get current change: show bookmarks if present, otherwise short change id
  jj_head_job = vim.fn.jobstart(
    { "jj", "log", "-r", "@", "--no-graph", "-T", "separate(' ', local_bookmarks, change_id.short(8))" },
    {
      stdout_buffered = true,
      on_stdout = function(_, data)
        if data and data[1] then
          jj_head = data[1]:gsub("%s+$", "")
        end
        vim.schedule(function()
          if package.loaded["lualine"] then
            require("lualine").refresh()
          end
        end)
      end,
    }
  )

  -- parse `jj status` for file change counts
  jj_status_job = vim.fn.jobstart({ "jj", "status", "--no-pager" }, {
    stdout_buffered = true,
    on_stdout = function(_, data)
      local added, modified, removed, conflicts = 0, 0, 0, 0
      for _, line in ipairs(data) do
        local code = line:sub(1, 1)
        if code == "A" then
          added = added + 1
        elseif code == "M" then
          modified = modified + 1
        elseif code == "D" then
          removed = removed + 1
        elseif code == "C" then
          conflicts = conflicts + 1
        end
      end
      jj_repo_status = { added = added, modified = modified, removed = removed, conflicts = conflicts }
      vim.schedule(function()
        if package.loaded["lualine"] then
          require("lualine").refresh()
        end
      end)
    end,
  })
end

vim.api.nvim_create_autocmd({ "BufWritePost", "FocusGained", "DirChanged" }, {
  callback = update_jj_status,
})

vim.defer_fn(update_jj_status, 100)

function M.branch(palette, active)
  local color = active and palette.dark_comment or palette.inactive_dark

  return {
    function()
      return jj_head
    end,
    icon = "\u{f0065}",
    color = color,
    padding = { left = 1, right = 0 },
    cond = function()
      return helpers.is_normal() and helpers.is_jj_repo() and jj_head ~= ""
    end,
  }
end

function M.repo_status(palette, active)
  local color = active and palette.dark_comment or palette.inactive_dark

  return {
    function()
      local parts = {}
      if jj_repo_status.added > 0 then
        table.insert(parts, "+" .. jj_repo_status.added)
      end
      if jj_repo_status.modified > 0 then
        table.insert(parts, "~" .. jj_repo_status.modified)
      end
      if jj_repo_status.removed > 0 then
        table.insert(parts, "-" .. jj_repo_status.removed)
      end
      if jj_repo_status.conflicts > 0 then
        table.insert(parts, "!" .. jj_repo_status.conflicts)
      end
      return table.concat(parts, " ")
    end,
    color = color,
    cond = function()
      return helpers.is_normal()
        and helpers.is_jj_repo()
        and (
          jj_repo_status.added > 0
          or jj_repo_status.modified > 0
          or jj_repo_status.removed > 0
          or jj_repo_status.conflicts > 0
        )
    end,
  }
end

return M
