-- generated by ai
-- picker-ignore: gitignore-style filtering for Snacks pickers.
--
-- Applied through a picker `transform` (return false drops the item) so it works
-- uniformly for git_files/files/smart/grep/recent. This matters because
-- git_files runs `git ls-files` and ignores the `exclude` option entirely, so
-- exclude-based filtering can't hide tracked-but-generated files.
--
-- Two layers are unioned:
--   * global : stdpath('config')/data/pickerignore
--   * project: nearest `.pickerignore` walking up from the picker's cwd
-- Patterns use gitignore-ish syntax (see the global file for a description).

local uv = vim.uv or vim.loop

local M = {}

local GLOBAL_FILE = vim.fn.stdpath("config") .. "/data/pickerignore"
local PROJECT_NAME = ".pickerignore"
local RECHECK_MS = 1000

-- compile one gitignore-ish pattern into rule(s) of LSP-glob lpegs
local function compile_pattern(raw, rules)
  local pat = raw:gsub("%s+$", "")
  if pat == "" or pat:sub(1, 1) == "#" then return end
  if pat:sub(1, 2) == "\\#" then pat = pat:sub(2) end

  local negate = pat:sub(1, 1) == "!"
  if negate then pat = pat:sub(2) end
  if pat == "" then return end

  local dir_only = pat:sub(-1) == "/"
  pat = pat:gsub("/+$", "")
  local anchored = pat:sub(1, 1) == "/"
  pat = pat:gsub("^/+", "")
  if pat == "" then return end

  -- a pattern with no interior slash matches at any depth (gitignore basename
  -- rule); an anchored or path-bearing pattern matches from the base dir
  local has_slash = pat:find("/") ~= nil
  local base = (anchored or has_slash) and pat or ("**/" .. pat)

  -- files under a matched directory (covers dir-only and plain dir names), plus
  -- the path/name itself as a file unless the pattern is explicitly dir-only
  local globs = { base .. "/**" }
  if not dir_only then globs[#globs + 1] = base end

  local compiled = {}
  for _, g in ipairs(globs) do
    local ok, lp = pcall(vim.glob.to_lpeg, g)
    if ok then compiled[#compiled + 1] = lp end
  end
  if #compiled > 0 then
    rules[#rules + 1] = { globs = compiled, negate = negate }
  end
end

-- build a matcher from raw pattern lines; match() honors last-match-wins so a
-- later `!negation` line can re-include a path an earlier line ignored
local function build_matcher(lines)
  local rules = {}
  for _, line in ipairs(lines) do
    compile_pattern(line, rules)
  end
  return function(relpath)
    local ignored = false
    for _, rule in ipairs(rules) do
      for _, g in ipairs(rule.globs) do
        if g:match(relpath) == #relpath + 1 then
          ignored = not rule.negate
          break
        end
      end
    end
    return ignored
  end
end

local function read_lines(path)
  local f = io.open(path, "r")
  if not f then return nil end
  local lines = {}
  for line in f:lines() do
    lines[#lines + 1] = line
  end
  f:close()
  return lines
end

-- file path -> { mtime, checked_at, matcher }; matcher is false when absent
local cache = {}

-- load+compile the matcher for `path`, rebuilding on mtime change (rechecked at
-- most once per RECHECK_MS to keep large finder runs cheap)
local function matcher_for_file(path)
  if not path then return nil end
  local now = uv.now()
  local entry = cache[path]
  if entry and (now - entry.checked_at) < RECHECK_MS then
    return entry.matcher or nil
  end
  local stat = uv.fs_stat(path)
  local mtime = stat and stat.mtime and (stat.mtime.sec * 1000000000 + (stat.mtime.nsec or 0)) or nil
  if entry and entry.mtime == mtime then
    entry.checked_at = now
    return entry.matcher or nil
  end
  local matcher = false
  local lines = stat and read_lines(path)
  if lines then matcher = build_matcher(lines) end
  cache[path] = { mtime = mtime, checked_at = now, matcher = matcher }
  return matcher or nil
end

-- resolve the project .pickerignore by walking up from `dir`; cached per dir
local project_file_cache = {}
local function project_file_for(dir)
  if not dir or dir == "" then return nil end
  local now = uv.now()
  local cached = project_file_cache[dir]
  if cached and (now - cached.checked_at) < RECHECK_MS then
    return cached.path
  end
  local found = vim.fs.find(PROJECT_NAME, { path = dir, upward = true })[1]
  project_file_cache[dir] = { path = found, checked_at = now }
  return found
end

local function relpath(abs, base)
  if base and base ~= "" then
    base = (vim.fs.normalize(base):gsub("/+$", ""))
    if abs:sub(1, #base + 1) == base .. "/" then
      return abs:sub(#base + 2)
    end
  end
  return abs
end

-- absolute, normalized path for a picker item
local function item_path(item)
  local p = Snacks.picker.util.path(item)
  if not p and item.file then
    p = (item.cwd and not item.file:match("^/")) and (item.cwd .. "/" .. item.file) or item.file
  end
  return p and vim.fs.normalize(p) or nil
end

-- returns true if the item should be dropped from the picker
function M.is_ignored(item)
  local abs = item_path(item)
  if not abs then return false end

  local base = vim.fs.normalize(item.cwd or vim.fn.getcwd())

  local global = matcher_for_file(GLOBAL_FILE)
  if global and global(relpath(abs, base)) then return true end

  local pfile = project_file_for(base)
  if pfile then
    local project = matcher_for_file(pfile)
    if project and project(relpath(abs, vim.fs.dirname(pfile))) then return true end
  end
  return false
end

-- Snacks picker transform: return false to drop the item, nil to keep it
function M.transform(item)
  local ok, ignored = pcall(M.is_ignored, item)
  if ok and ignored then return false end
end

-- forget compiled matchers (e.g. after editing an ignore file in this session)
function M.clear_cache()
  cache = {}
  project_file_cache = {}
end

return M
